import { mkdirSync, readFileSync, writeFileSync, existsSync, chmodSync } from 'node:fs';
import { dirname, join } from 'node:path';
import {
  BRIDGE_MARKER,
  isVeyraManagedCommand,
  resolveBridgeRoot,
  type BridgeManifest,
} from './paths.js';

type HookHandler = {
  type?: string;
  command?: string;
  timeout?: number;
  statusMessage?: string;
  [key: string]: unknown;
};

type HookGroup = {
  matcher?: string;
  hooks?: HookHandler[];
  [key: string]: unknown;
};

type HooksConfig = Record<string, HookGroup[]>;

function readJsonFile(path: string): Record<string, unknown> {
  if (!existsSync(path)) {
    return {};
  }
  try {
    const raw = JSON.parse(readFileSync(path, 'utf8')) as unknown;
    if (raw && typeof raw === 'object' && !Array.isArray(raw)) {
      return raw as Record<string, unknown>;
    }
  } catch {
    // corrupt — start fresh merge base
  }
  return {};
}

function writeJsonFile(path: string, data: unknown): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, `${JSON.stringify(data, null, 2)}\n`, 'utf8');
}

function shellBridgeScript(cliEntry: string, adapter: 'claude-code' | 'codex'): string {
  return `#!/usr/bin/env sh
# ${BRIDGE_MARKER} — generated by \`veyra bridge install\`. Do not edit by hand.
set -eu
exec node "${cliEntry}" hook --adapter=${adapter}
`;
}

function veyraHookHandler(scriptPath: string, statusMessage: string): HookHandler {
  return {
    type: 'command',
    command: `"${scriptPath}"`,
    timeout: 15,
    statusMessage,
  };
}

function stripManaged(groups: HookGroup[] | undefined): HookGroup[] {
  if (!groups) {
    return [];
  }
  return groups
    .map((group) => {
      const hooks = (group.hooks ?? []).filter(
        (h) => !(typeof h.command === 'string' && isVeyraManagedCommand(h.command)),
      );
      return { ...group, hooks };
    })
    .filter((group) => (group.hooks?.length ?? 0) > 0);
}

function ensureManagedGroup(
  groups: HookGroup[],
  matcher: string | undefined,
  handler: HookHandler,
): HookGroup[] {
  const cleaned = stripManaged(groups);
  const existing = cleaned.find((g) => (g.matcher ?? '') === (matcher ?? ''));
  if (existing) {
    return cleaned.map((g) =>
      g === existing ? { ...g, hooks: [...(g.hooks ?? []), handler] } : g,
    );
  }
  return [...cleaned, matcher ? { matcher, hooks: [handler] } : { hooks: [handler] }];
}

function buildClaudeHooksPatch(scriptPath: string): HooksConfig {
  const handler = veyraHookHandler(scriptPath, 'VEYRA Watchdog');
  return {
    PreToolUse: [{ hooks: [handler] }],
    PostToolUse: [
      {
        hooks: [{ ...handler, statusMessage: 'VEYRA Watchdog (post)' }],
      },
    ],
    UserPromptSubmit: [
      {
        hooks: [{ ...handler, statusMessage: 'VEYRA Watchdog (prompt)' }],
      },
    ],
  };
}

function installClaudeHooks(
  settingsPath: string,
  scriptPath: string,
  patchPath: string,
): { mode: 'live' | 'patch'; error?: string; backupPath?: string } {
  const patch = buildClaudeHooksPatch(scriptPath);
  try {
    let backupPath: string | undefined;
    if (existsSync(settingsPath)) {
      // Keep a restore point for uninstall — do not overwrite an existing backup
      // from an earlier install in this plane.
      backupPath = `${settingsPath}.veyra-backup`;
      if (!existsSync(backupPath)) {
        writeFileSync(backupPath, readFileSync(settingsPath, 'utf8'), 'utf8');
      }
      // Also keep a timestamped copy for forensics
      writeFileSync(
        `${settingsPath}.veyra-backup-${Date.now()}`,
        readFileSync(settingsPath, 'utf8'),
        'utf8',
      );
    }
    const settings = readJsonFile(settingsPath);
    const hooks = (settings['hooks'] as HooksConfig | undefined) ?? {};
    const handler = veyraHookHandler(scriptPath, 'VEYRA Watchdog');

    const next: HooksConfig = {
      ...hooks,
      PreToolUse: ensureManagedGroup(hooks['PreToolUse'] ?? [], undefined, handler),
      PostToolUse: ensureManagedGroup(hooks['PostToolUse'] ?? [], undefined, {
        ...handler,
        statusMessage: 'VEYRA Watchdog (post)',
      }),
      UserPromptSubmit: ensureManagedGroup(hooks['UserPromptSubmit'] ?? [], undefined, {
        ...handler,
        statusMessage: 'VEYRA Watchdog (prompt)',
      }),
    };

    writeJsonFile(settingsPath, { ...settings, hooks: next });
    writeJsonFile(patchPath, { hooks: patch });
    return { mode: 'live', ...(backupPath ? { backupPath } : {}) };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    writeJsonFile(patchPath, {
      hooks: patch,
      note: 'Could not write .claude/settings.json (often blocked in sandboxed agents). Merge this hooks object into .claude/settings.json manually, or re-run `veyra bridge install` in a normal terminal.',
      error: message,
    });
    return { mode: 'patch', error: message };
  }
}

function uninstallClaudeHooks(settingsPath: string, backupPath?: string): void {
  // Prefer full restore from pre-install backup when available
  if (backupPath && existsSync(backupPath)) {
    writeFileSync(settingsPath, readFileSync(backupPath, 'utf8'), 'utf8');
    return;
  }
  const stableBackup = `${settingsPath}.veyra-backup`;
  if (existsSync(stableBackup)) {
    writeFileSync(settingsPath, readFileSync(stableBackup, 'utf8'), 'utf8');
    return;
  }

  if (!existsSync(settingsPath)) {
    return;
  }
  const settings = readJsonFile(settingsPath);
  const hooks = (settings['hooks'] as HooksConfig | undefined) ?? {};
  const next: HooksConfig = {};
  for (const [event, groups] of Object.entries(hooks)) {
    const cleaned = stripManaged(groups);
    if (cleaned.length > 0) {
      next[event] = cleaned;
    }
  }
  if (Object.keys(next).length === 0) {
    const { hooks: _removed, ...rest } = settings;
    writeJsonFile(settingsPath, rest);
  } else {
    writeJsonFile(settingsPath, { ...settings, hooks: next });
  }
}

function installCodexHooks(
  hooksPath: string,
  scriptPath: string,
): { backupPath?: string } {
  let backupPath: string | undefined;
  if (existsSync(hooksPath)) {
    backupPath = `${hooksPath}.veyra-backup`;
    if (!existsSync(backupPath)) {
      writeFileSync(backupPath, readFileSync(hooksPath, 'utf8'), 'utf8');
    }
  }

  const file = readJsonFile(hooksPath);
  // Codex uses either top-level event keys or nested under "hooks"
  const nested = file['hooks'];
  const base: HooksConfig =
    nested && typeof nested === 'object' && !Array.isArray(nested)
      ? (nested as HooksConfig)
      : (file as HooksConfig);

  const handler = veyraHookHandler(scriptPath, 'VEYRA Watchdog');
  const next: HooksConfig = {
    ...base,
    PreToolUse: ensureManagedGroup(base['PreToolUse'] ?? [], undefined, handler),
    PostToolUse: ensureManagedGroup(base['PostToolUse'] ?? [], undefined, {
      ...handler,
      statusMessage: 'VEYRA Watchdog (post)',
    }),
    UserPromptSubmit: ensureManagedGroup(base['UserPromptSubmit'] ?? [], undefined, {
      ...handler,
      statusMessage: 'VEYRA Watchdog (prompt)',
    }),
  };

  writeJsonFile(hooksPath, {
    description: 'VEYRA Watchdog live bridge (merge-safe)',
    hooks: next,
  });
  return backupPath ? { backupPath } : {};
}

function uninstallCodexHooks(hooksPath: string, backupPath?: string): void {
  if (backupPath && existsSync(backupPath)) {
    writeJsonFile(hooksPath, JSON.parse(readFileSync(backupPath, 'utf8')) as unknown);
    return;
  }
  const stableBackup = `${hooksPath}.veyra-backup`;
  if (existsSync(stableBackup)) {
    writeJsonFile(hooksPath, JSON.parse(readFileSync(stableBackup, 'utf8')) as unknown);
    return;
  }

  if (!existsSync(hooksPath)) {
    return;
  }
  const file = readJsonFile(hooksPath);
  const nested = file['hooks'];
  const base: HooksConfig =
    nested && typeof nested === 'object' && !Array.isArray(nested)
      ? (nested as HooksConfig)
      : (file as HooksConfig);

  const next: HooksConfig = {};
  for (const [event, groups] of Object.entries(base)) {
    if (event === 'description') continue;
    const cleaned = stripManaged(Array.isArray(groups) ? groups : []);
    if (cleaned.length > 0) {
      next[event] = cleaned;
    }
  }

  if (Object.keys(next).length === 0) {
    writeJsonFile(hooksPath, { description: 'VEYRA Watchdog live bridge (uninstalled)' });
  } else {
    writeJsonFile(hooksPath, { description: file['description'], hooks: next });
  }
}

export type InstallOptions = {
  adapters: Array<'claude-code' | 'codex'>;
  cwd?: string;
};

export type InstallResult = {
  projectRoot: string;
  adapters: Array<'claude-code' | 'codex'>;
  claudeSettingsPath: string;
  claudePatchPath: string;
  claudeMode: 'live' | 'patch' | 'skipped';
  claudeError?: string;
  codexHooksPath: string;
  scripts: string[];
};

export function installBridge(options: InstallOptions): InstallResult {
  const paths = resolveBridgeRoot(options.cwd);
  mkdirSync(paths.hooksDir, { recursive: true });
  const claudePatchPath = join(paths.hooksDir, 'claude.settings.patch.json');

  const scripts: string[] = [];
  let claudeMode: InstallResult['claudeMode'] = 'skipped';
  let claudeError: string | undefined;
  let claudeSettingsBackup: string | undefined;
  let codexHooksBackup: string | undefined;

  // Preserve backup paths from a prior install so uninstall can still restore
  let prior: BridgeManifest | null = null;
  if (existsSync(paths.manifestPath)) {
    try {
      prior = JSON.parse(readFileSync(paths.manifestPath, 'utf8')) as BridgeManifest;
    } catch {
      prior = null;
    }
  }

  if (options.adapters.includes('claude-code')) {
    writeFileSync(paths.claudeScriptPath, shellBridgeScript(paths.cliEntry, 'claude-code'), {
      encoding: 'utf8',
      mode: 0o755,
    });
    chmodSync(paths.claudeScriptPath, 0o755);
    const claude = installClaudeHooks(
      paths.claudeSettingsPath,
      paths.claudeScriptPath,
      claudePatchPath,
    );
    claudeMode = claude.mode;
    claudeError = claude.error;
    claudeSettingsBackup = claude.backupPath ?? prior?.claudeSettingsBackup;
    scripts.push(paths.claudeScriptPath);
  }

  if (options.adapters.includes('codex')) {
    writeFileSync(paths.codexScriptPath, shellBridgeScript(paths.cliEntry, 'codex'), {
      encoding: 'utf8',
      mode: 0o755,
    });
    chmodSync(paths.codexScriptPath, 0o755);
    const codex = installCodexHooks(paths.codexHooksPath, paths.codexScriptPath);
    codexHooksBackup = codex.backupPath ?? prior?.codexHooksBackup;
    scripts.push(paths.codexScriptPath);
  }

  const manifest: BridgeManifest = {
    version: '0.1.0',
    installedAt: new Date().toISOString(),
    adapters: options.adapters,
    cliEntry: paths.cliEntry,
    ...(claudeSettingsBackup ? { claudeSettingsBackup } : {}),
    ...(codexHooksBackup ? { codexHooksBackup } : {}),
  };
  writeFileSync(paths.manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, 'utf8');

  return {
    projectRoot: paths.projectRoot,
    adapters: options.adapters,
    claudeSettingsPath: paths.claudeSettingsPath,
    claudePatchPath,
    claudeMode,
    ...(claudeError !== undefined ? { claudeError } : {}),
    codexHooksPath: paths.codexHooksPath,
    scripts,
  };
}

export function uninstallBridge(cwd: string = process.cwd()): {
  projectRoot: string;
  removed: string[];
  restored: boolean;
} {
  const paths = resolveBridgeRoot(cwd);
  const removed: string[] = [];
  let restored = false;

  let manifest: BridgeManifest | null = null;
  if (existsSync(paths.manifestPath)) {
    try {
      manifest = JSON.parse(readFileSync(paths.manifestPath, 'utf8')) as BridgeManifest;
    } catch {
      manifest = null;
    }
  }

  const hadClaudeBackup =
    Boolean(manifest?.claudeSettingsBackup && existsSync(manifest.claudeSettingsBackup)) ||
    existsSync(`${paths.claudeSettingsPath}.veyra-backup`);

  uninstallClaudeHooks(paths.claudeSettingsPath, manifest?.claudeSettingsBackup);
  if (existsSync(paths.claudeSettingsPath)) {
    removed.push(paths.claudeSettingsPath);
  }
  if (hadClaudeBackup) {
    restored = true;
  }

  uninstallCodexHooks(paths.codexHooksPath, manifest?.codexHooksBackup);
  if (existsSync(paths.codexHooksPath)) {
    removed.push(paths.codexHooksPath);
  }

  if (existsSync(paths.manifestPath)) {
    writeFileSync(
      paths.manifestPath,
      `${JSON.stringify(
        {
          version: '0.1.0',
          uninstalledAt: new Date().toISOString(),
          adapters: [],
          cliEntry: paths.cliEntry,
        },
        null,
        2,
      )}\n`,
      'utf8',
    );
    removed.push(paths.manifestPath);
  }

  return { projectRoot: paths.projectRoot, removed, restored };
}

export function bridgeStatus(cwd: string = process.cwd()): {
  projectRoot: string;
  manifest: BridgeManifest | null;
  claudeInstalled: boolean;
  codexInstalled: boolean;
  claudeSettingsPath: string;
  codexHooksPath: string;
} {
  const paths = resolveBridgeRoot(cwd);
  let manifest: BridgeManifest | null = null;
  if (existsSync(paths.manifestPath)) {
    try {
      manifest = JSON.parse(readFileSync(paths.manifestPath, 'utf8')) as BridgeManifest;
    } catch {
      manifest = null;
    }
  }

  const claude = readJsonFile(paths.claudeSettingsPath);
  const claudeHooks = (claude['hooks'] as HooksConfig | undefined) ?? {};
  const claudeInstalled = Object.values(claudeHooks).some((groups) =>
    (groups ?? []).some((g) =>
      (g.hooks ?? []).some((h) => typeof h.command === 'string' && isVeyraManagedCommand(h.command)),
    ),
  );

  const codexFile = readJsonFile(paths.codexHooksPath);
  const codexNested = codexFile['hooks'];
  const codexBase: HooksConfig =
    codexNested && typeof codexNested === 'object' && !Array.isArray(codexNested)
      ? (codexNested as HooksConfig)
      : (codexFile as HooksConfig);
  const codexInstalled = Object.values(codexBase).some(
    (groups) =>
      Array.isArray(groups) &&
      groups.some((g) =>
        (g.hooks ?? []).some(
          (h) => typeof h.command === 'string' && isVeyraManagedCommand(h.command),
        ),
      ),
  );

  return {
    projectRoot: paths.projectRoot,
    manifest,
    claudeInstalled,
    codexInstalled,
    claudeSettingsPath: paths.claudeSettingsPath,
    codexHooksPath: paths.codexHooksPath,
  };
}
